# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Initial status
        run: |
          pwd
          ls
        
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          ref: main
      - name: Second status
        run: |
           echo $GITHUB_WORKSPACE
           date > changedfiles.txt
           pwd
           cat changedfiles.txt
           ls
           git remote -v
           git status
           git config --global user.name 'Your Name'
           git config --global user.email 'your-username@users.noreply.github.com'
           git add -A
           git commit -m "Automated report"
           git push origin main
      - uses: actions/checkout@v2
        with:
          ref: main
      - name: Second status
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git fetch
          git branch -a
          git checkout release2
          git branch -a
          git pull origin/main
          git merge --allow-unrelated-histories origin/main
           
      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
